POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpbW9uIiwiaWQiOiI1ZDI3Mjc5ZTQzODM4MzFhNzFhMDhlMGQiLCJpYXQiOjE1NjI4NTIzOTN9.yyDrWNGvhuUtgVqXensufJgEZZx9TYV9_O3y70VnQho

{
  "title": "This is a newer test",
  "author": "Simon",
  "url": "www.google.com",
  "likes": "30"
}